#!/usr/bin/python3
#
#  Copyright (C) Ronan Brunner 2021
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
##########################################################################################################
import argparse
import sqlite3
import sys, os
from random import shuffle
##########################################################################################################
parser       = argparse.ArgumentParser(description='Create a playlist from jellyfin favorites.')

parser.add_argument('--database', '-d', dest='database', action='store',
                    default=None, type=str, required=True,
                    help='Jellyfin database file')

parser.add_argument('--shuffle', '-s', dest='shuffle', action='store_const',
                    default=0, const=1,
                    help='Shuffle the playlist order')

args         = parser.parse_args()
##########################################################################################################
con = sqlite3.connect(args.database)
cur = con.cursor()

favourites = {}

for row in cur.execute('SELECT userId,key FROM UserDatas WHERE isFavorite=1'):
    userid = row[0]
    key    = row[1]
    if userid not in favourites:
        favourites[userid] = list()
    favourites[userid].append(key)

for userid in favourites:
    print('Favourites for userid='+str(userid))
    entries = list()
    for userdatakey in favourites[userid]:
        for entry in cur.execute('SELECT Path FROM TypedBaseItems WHERE type="MediaBrowser.Controller.Entities.Audio.Audio" AND UserDataKey="' + userdatakey + '"'):
            entries.append(entry[0])
    if args.shuffle:
        shuffle(entries)
    filename='00-Favourites-'+str(userid)+'.m3u'
    m3u = open(filename, 'w')
    for entry in entries:
        m3u.write(entry+'\n')
    m3u.close()
    print('Wrote '+str(len(entries))+' to file '+filename)
    
